[build]
  # Directory with the built static site
  publish = "."
  # Your build command
  command = "echo 'No build command needed - static files only'"
  # Directory with Netlify Functions
  functions = "netlify/functions"

# Proxy API requests to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Handle direct navigation for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200